timeout: 7200s # 2 hours
substitutions:
  _ANOTHER_VAR: 'test'
  _GRAALVM_VERSION: '22.3.0'
steps:
  # GraalVM build
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}", "--build-arg=GRAALVM_VERSION=$_GRAALVM_VERSION", "."]
    env:
    dir: java/graalvm
    id: graalvm-build
    waitFor: ["-"]
  - name: gcr.io/gcp-runtimes/structure_test
    args:
      ["-i", "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}", "--config", "java/graalvm.yaml", "-v"]
    waitFor: ["graalvm-build"]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "tag",
        "gcr.io/$PROJECT_ID/graalvm:${_GRAALVM_VERSION}",
        "gcr.io/cloud-devrel-public-resources/graalvm:${_GRAALVM_VERSION}",
      ]
    waitFor: ["graalvm-build"]
